services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

script:
  - docker ps -a
  - docker-compose -f docker-compose.test.yml run --rm test-api coverage run -m pytest -v
  - docker-compose -f docker-compose.test.yml run --rm test-api flake8

branches:
  only:
    - master
