services:
  - docker

addons:
  apt:
    packages:
      - docker-ce


before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - cp .env.test.example .env.test

script:
  - mkdir shared
  - docker-compose -f docker-compose.test.yml build
  - docker-compose -f docker-compose.test.yml run --rm test-api coverage run -m pytest -v
  - docker-compose -f docker-compose.test.yml run --rm test-api coverage xml
  - docker-compose -f docker-compose.test.yml run -v "$PWD/shared:/backend/shared" --rm test-api mv coverage.xml shared/
  - docker-compose -f docker-compose.test.yml run --rm test-api flake8
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - docker-compose -f docker-compose.test.yml stop
  - docker-compose -f docker-compose.test.yml rm -rf

branches:
  only:
    - master
