services:
  - docker

script:
  - docker ps -a
  - docker-compose -f docker-compose.test.yml run --rm test-api coverage run -m pytest -v
  - docker-compose -f docker-compose.test.yml run --rm test-api flake8

branches:
  only:
    - master
