version: '3.5'
services:
  redis-cache:
    image: redis:alpine
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=flask_api
    ports:
      - 5432:5432
    expose:
      - 5432
  api:
    container_name: backend_api
    depends_on:
      - db
      - redis-cache
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - './backend:/backend'
    ports:
      - 5000:5000
    expose:
      - 5000
